---
# k8s
k8s_user: ansible
k8s_reset_cluster: false                      # Resets and re-initializes cluster, be absolutely sure if you do this!
k8s_join_only: false                          # skip k8s initialization, e.g. when only joining a new node
k8s_replace_kube_proxy: true                  # disable kube proxy, e.g. to rely on Cilium's eBPF implementation.
k8s_kube_proxy_replacement: strict
k8s_control_plane_endpoint: control-plane
k8s_master_control_plane_ip: 192.168.178.101
k8s_pod_network_cidr: 10.100.0.0/16
k8s_service_cidr: 10.200.0.0/16
k8s_cri_socket: /run/containerd/containerd.sock

# Cilium
cilium_install: true
cilium_version: v1.10.4
cilium_chart_version: v1.10.4
cilium_hubble: false
cilium_hubble_ui: false
cilium_hubble_relay: false # requires cilium_hubble=true

# Sealed-Secrets
sealed_secrets_install: true
sealed_secrets_version: v0.17.3
sealed_secrets_chart_version: 2.1.4

proc_arch:
  name: aarch64 # x86_64
  name_alt: arm64 # amd64

# Common
common_hostname: "{{ name }}"
common_update_hosts_file: true

# Add entry for master node to /etc/hosts. Once the cluster
# is fully initialized, k8s_control_plane_endpoint should
# point to a LB in order to achieve HA.
common_host_entries:
  - host: "{{ k8s_control_plane_endpoint }}"
    ip: "{{ k8s_master_control_plane_ip }}"

# Users config
users:
  - username: ansible
    group: ansible
    authorized_keys:
      - "{{ lookup('file', '~/.ssh/id_ansible.pub') }}"

# Firewall config
firewalld_disable_firewalls:
  - ufw
firewalld_services:
  - zone: public
    service_names:
      - ssh
    state: disabled  # reconfigured with custom port, see security settings below

# Security config
security_ssh_port: 2848
security_sudoers_passwordless:
  - ansible
